name: Merge Request CI

on:
  pull_request:
    branches: [development]

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile -non-interactive --silent
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn run build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn run lint
